# Use the official MySQL image from the Docker Hub
FROM public.ecr.aws/docker/library/mysql:latest

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=music_db

# Expose the MySQL port
EXPOSE 3306
