version: '3.8'

services:
  db:
    build: .
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: ./php
    volumes:
      - ./php:/var/www/html
    ports:
      - "8080:80"

volumes:
  db_data: